services:
  airflow-webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: airflow-webserver
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - '9090:9090'
    command: webserver
    depends_on:
      - airflow-init

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler
    depends_on:
      - airflow-init

  airflow-init:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: airflow-init
    entrypoint: /bin/bash
    command: >
               -c " 
                    airflow db init &&

                    airflow users create \
                    --username **** \
                    --firstname **** \
                    --lastname **** \
                    --role Admin \
                    --email **** \
                    --password ****
                  "
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
