services:
  airflow-webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: airflow-webserver
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://root:airfwDB9090@db/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - '9090:9090'
    command: webserver --port 9090
    depends_on:
      - airflow-init
      - db

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://root:airfwDB9090@db/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler
    depends_on:
      - airflow-init
      - db

  airflow-init:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: airflow-init
    entrypoint: /bin/bash
    command: >
               -c " 
                    airflow db init &&

                    airflow users create --username gabz --firstname Gabriel --lastname Ferreira --role Admin --email gabs.ferr08@gmail.com --password GA96biel
                  "
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://root:airfwDB9090@db/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=airfwDB9090
      - MYSQL_DATABASE=airflow
    ports:
      - '9191:3306' # <-- Para se precisarmos acessar o banco do airflow mais tarde
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
